### ISSUE TITLE
TypeError: dispatcher for __array_function__ did not return an iterable

### ISSUE THREAD

**Issue by helena-panda** [pmenczel/bosonic-heom#1]
Ask for help!  (system:  anaconda (python3.8) in windows 10) ,thanks for concern!
There is an error:   Example 1 in sample
`solver1 = HEOM(HQ, [influence_phase1], cutoff_zeroT)
result1 = solver1.solve(rho0, tlist, e_ops=[excited], options=options)`

error info:

TypeError                                 Traceback (most recent call last)
Input In [8], in <cell line: 2>()
      1 solver1 = HEOM(HQ, [influence_phase1], cutoff_zeroT)
----> 2 result1 = solver1.solve(rho0, tlist, e_ops=[excited], options=options)

File C:\data\python\bosonic\bosonic_heom\heom.py:202, in HEOM.solve(self, rho0, tlist, e_ops, dynamic_hamiltonian, options, **kwargs)
    199         result.expect[i].append(exp)
    201 options.normalize_output = False # important! since our "hamiltonian" is not hermitian
--> 202 sesolve(h_param, extended_rho0, tlist, e_ops=callback, options=options)
    203 return result

File C:\Anaconda3\envs\bofin_env\lib\site-packages\qutip\sesolve.py:136, in sesolve(H, psi0, tlist, e_ops, args, options, progress_bar, _safe_mode)
    133     v = psi0.full().ravel('F')
    134     func(0., v, *ode_args) + v
--> 136 res = _generic_ode_solve(func, ode_args, psi0, tlist, e_ops, options,
    137                          progress_bar, dims=psi0.dims)
    138 if e_ops_dict:
    139     res.expect = {e: res.expect[n]
    140                   for n, e in enumerate(e_ops_dict.keys())}

File C:\Anaconda3\envs\bofin_env\lib\site-packages\qutip\sesolve.py:362, in _generic_ode_solve(func, ode_args, psi0, tlist, e_ops, opt, progress_bar, dims)
    358         output.states.append(Qobj(fdata, dims=dims, fast='mc'))
    360 if expt_callback:
    361     # use callback method
--> 362     output.expect.append(e_ops(t, Qobj(cdata, dims=dims)))
    364 if oper_evo:
    365     for m in range(n_expt_op):

File C:\data\python\bosonic\bosonic_heom\heom.py:186, in HEOM.solve.<locals>.callback(time, extended_state)
    185 def callback(time, extended_state):
--> 186     state = HEOM._extract_ado(extended_state, self._num_ados, 0)
    187     hamiltonian = self.static_hamiltonian
    188     if dynamic_hamiltonian is not None:

File C:\data\python\bosonic\bosonic_heom\heom.py:401, in HEOM._extract_ado(extended_operator, extended_dim, row)
    398 if (dim * extended_dim != extended_operator.shape[0]) or (hilbert_dim**2 != dim):
    399     raise ValueError
--> 401 qobj = Qobj(inpt=extended_operator.data[(row * dim):((row+1) * dim), :],
    402             dims=[[[hilbert_dim], [hilbert_dim]], 1],
    403             shape=new_shape,
    404             type="operator-ket")
    405 return vector_to_operator(qobj)

File C:\Anaconda3\envs\bofin_env\lib\site-packages\qutip\qobj.py:336, in Qobj.__init__(self, inpt, dims, shape, type, isherm, copy, fast, superrep, isunitary)
    329         self.superrep = 'super'
    331 # While the obvious check would be != that would fail valid
    332 # use cases such as enr_fock and other enr_ functions.
    333 # This does leave open the possibility of data still being
    334 # misused such as Qobj(complex[n**2][1], dims = [[n],[n]])
    335 if (self._data.shape[0] > np.prod(np.hstack(self.dims[0])) or
--> 336    self._data.shape[1] > np.prod(np.hstack(self.dims[1]))) and \
    337    self.type != 'super':
    339     raise ValueError(f"Qobj has smaller dims {self.dims} " +
    340                      f"than underlying shape {self._data.shape}")
    342 # clear type cache

File <__array_function__ internals>:5, in hstack(*args, **kwargs)

TypeError: dispatcher for __array_function__ did not return an iterable

**Comment by pmenczel** [comment]
Thank you for notifying me. The bug was created due to a change made in QuTiP 4.6.3. It should be fixed now.
